### PR TITLE
4.x - move ConsoleShell to under command namespace

### PR DESCRIPTION
**Pull request by saeideng**

### CODE REVIEW

**Comment by ADmad** [comment]
Do people use this REPL shell? I have never heard anyone mention using it. The lib the Console shell relies on pulls in a symfony dependency which overrides our debug() function.

**Comment by dakota** [comment]
I personally use it multiple times a day. Would be sad to see it go.

Also, I prefer the symfony `debug()` and `dd()` output (it's super interactive and easier to find what I'm looking for)

**Comment by dereuromark** [comment]
@dakota Wouldnt a plugin solution suffice here?

**Comment by dereuromark** [comment]
> Also, I prefer the symfony debug() and dd() output (it's super interactive and easier to find what I'm looking for)

I agree that they have the better debug tooling here in terms of usability, but secretly overwriting the core ones is a nogo IMO. This should be a clear opt-in behavior you want to have, rather than getting this by accident right now.

**Comment by ADmad** [comment]
> I agree that they have the better debug tooling here in terms of usability, but secretly overwriting the core ones is a nogo IMO. This should be a clear opt-in behavior you want to have, rather than getting this by accident right now.

Exactly.

**Comment by markstory** [comment]
I also use the repl shell quite a bit.

**Comment by saeideng** [comment]
we can remove the class and docs if necessary later 
I merged for now , we have to mention in docs before removing ( if needed )

**Pull request merged**
