### PR TITLE
Add warning to others

### PR DESCRIPTION
**Pull request by ZoeB**
Learned the hard way.

### CODE REVIEW

**Comment by josegonzalez** [comment]
Heh. Seems legit.

**Comment by markstory** [comment]
Thanks @ZoeB

**Comment by ZoeB** [comment]
You're welcome!  It was @AD7six's suggestion, if memory serves, so yet more people wouldn't make the same mistake. :)

**Comment by ADmad** [comment]
:cry:

**Comment by bravo-kernel** [comment]
:clap:

**Comment by ZoeB** [comment]
Ack, sorry!  Just how many ADs do you have here?

**Comment by ADmad** [comment]
Just 2 :)

**Comment by ZoeB** [comment]
Well thank you, ADmad. :)  Sorry for my terrible memory!  {{{Hugs!}}}

**Pull request merged**
