### PR TITLE
missing  onclick="this.classList.add('hidden');"

### PR DESCRIPTION
**Pull request by inoas**

### CODE REVIEW

**Comment by markstory** [comment]
Thanks :+1:

**Comment by ADmad** [comment]
Let's not add more inline js especially where it's not totally necessary.

**Comment by inoas** [comment]
@ADmad I am totally with you. All it does is bringing it in line with the rest of the flash message default app templates.

**Comment by ADmad** [comment]
I didn't know bake generated templates have this too :(

**Comment by inoas** [comment]
They have delete confirm js, nothing else.

**Pull request merged**
