### PR TITLE
Add call to Router::fullBaseUrl() in bootstrap.

### PR DESCRIPTION
**Pull request by ADmad**
Refs cakephp/cakephp#13672

### CODE REVIEW

**Comment by dereuromark** [comment]
Is there a soft migration path coming from 3.x? Like BC fallback etc?
Or do we need migration guide info on top?

**Comment by markstory** [comment]
@dereuromark It looks like this is an optimization to avoid parsing the URL inside of Router. The current `Router::fullBaseUrl()` is still backwards compatible with Configure only style setup.

**Comment by ADmad** [comment]
We should document this is migration guide though for most users upgrading won't have any issue.

The only users that can have a problem with this change are those use use `_ssl` key in URL arrays in commands/shells, since `Router::url()` now directly uses context to get host name instead of calling `Router::fullBaseUrl()` and then parsing the URL.

**Comment by markstory** [comment]
@ADmad What would we put in the migration guide for this? Perhaps to update their bootstrap.php based on what is in the current skeleton?

**Comment by ADmad** [comment]
@markstory Yes

**Pull request merged**
