### PR TITLE
auto-load-app-local

### LINKED ISSUE #707: Auto enable app_local.php and .env loading
Can we have that? That would make creating docker compose environments for cakephp a breeze regarding database credentials, cache settings etc

### PR DESCRIPTION
**Pull request by inoas**
fixes #707 (only app_local)

### CODE REVIEW

**Comment by dereuromark** [comment]
That only makes sense by not having the app.php in gitignore

**Comment by ADmad** [comment]
> That only makes sense by not having the app.php in gitignore

And having `app_local.php` in .gitignore.

**Comment by markstory** [comment]
Looks good to me :+1:

**Comment by dereuromark** [comment]
Closing in favor of https://github.com/cakephp/app/pull/713

**Pull request closed without merging**
