### PR TITLE
Add coverage composer script

### PR DESCRIPTION
**Pull request by dereuromark**
This is a super useful helper I use myself, and since we are now using composer scripts, here it goes:

    composer coverage

It will then write a full HTML coverage report to browse into /webroot/coverage/
Just browse afterwards to your

    http://example.local/coverage/index.html

and you can then click through the local coverage report generated.

### CODE REVIEW

**Comment by josegonzalez** [comment]
Should we add that directory to gitignore as well?

**Comment by chinpei215** [comment]
I am not in favor of this change. Why do you publish HTMLs under the webroot? If I were a hacker, I would try to access with `/coverage/` when I found a CakePHP3 app.

**Comment by markstory** [comment]
@chinpei215 Do you typically run tests on your production hosts?

**Comment by dereuromark** [comment]
This is for local Dev only if course. Check the docs, same tip ist already there as well.

**Comment by bravo-kernel** [comment]
Very useful. Since I dump my coverage files outside my vm's webroot... would it be possible to use an argument for the directory? Maybe default to webroot if no directory argument is given.

**Comment by chinpei215** [comment]
@markstory No, I don't.
@dereuromark If you run phpunit --coverage-html on local only, why do you need to publish it under the webroot? You can see any html files in your browser by using `file://` schema.

**Comment by dereuromark** [comment]
Nothing can happen live because without require dev dependencies there is no phpunit :) and the folder is gitignore and will never be commited.

**Comment by josegonzalez** [comment]
lets move it up a directory, maybe to `tmp`?

**Comment by bravo-kernel** [comment]
I actually think `webroot` would be a good default for novice users since that will always be browseable andt thus "just work", even on a remote vm, without requiring any additional trickery. Simple instruction for the book as well IMO.

**Comment by dereuromark** [comment]
Exactly what I was thinking :)

**Comment by ADmad** [comment]
Remember back in 1.x days how many live sites had `webroot/test.php`?

**Comment by bravo-kernel** [comment]
@ADmad fair point, would this not all be solved when using a directory argument (if technically possible)?

**Comment by antograssiot** [comment]
I don't he buy the gitignore argument.
Do you really think that novice users will use git to deploy their app ?

**Comment by dereuromark** [comment]
I am also fine with tmp dir ;) etc

**Comment by ADmad** [comment]
@bravo-kernel A directory argument with defaulting to `TMP` should be fine.

**Comment by dereuromark** [comment]
Someone wants to modify the PR?

**Comment by bravo-kernel** [comment]
@ADmad that would be awesome, without an argument this would be useless to me. Nice addition @dereuromark

**Comment by dereuromark** [comment]
I think we should rather get this going and merge, and improve it more over time. Discussing it dead is doing less here for all.

**Comment by thinkingmedia** [comment]
@dereuromark Correct me if I'm wrong, but doesn't the coverage report use relative paths as to allow it to be opened from any directory location. For example; you could write the reports to `app/tmp/coverage` and just double click the `index.html` file to view the report. It doesn't need a web service or webroot.

**Comment by dereuromark** [comment]
The idea is to allow local URLs to quickly be used here, e.g. when you set up your vhost via cakebox and my-app.local, you just browse to my-app.local/coverage.
It is super easy this way - and due to the fact of require-dev only happening/possible for local dev.

**Comment by thinkingmedia** [comment]
@dereuromark okay, this looks good to me 👍 

If someone doesn't like it. They don't have to run it or they can change it.

**Comment by bravo-kernel** [comment]
@dereuromark could be me but I thought the discussion was already over and we were just waiting for the requested change.

> add a --directory argument defaulting to tmp

**Comment by dereuromark** [comment]
@bravo-kernel then please do that yourself afterwards.

**Comment by bravo-kernel** [comment]
@dereuromark sorry but I think it will be best for me to leave this discussion. Could be the flu but I'm getting a very weird feeling about this PR, not even seeing the `tmp` change feels the opposite of :heart somehow.

**Comment by dereuromark** [comment]
We just discussed that this is not comparable to any of the issues of 2.x days - the comparison is flawed.
There are no issues here.
And you yourself said, that it should be simple for newbies, and we all agree that it is easily modifyable if anyone wants to have it differently for their apps.

A follow up PR can still fine tune more, but that will need a whole lot of more discussion then and is out of scope of this simple addition here right now IMO.

**Comment by dereuromark** [comment]
I do listen, and I do value @bravo-kernel s feedback.
But all that now happened was a perfectly fine PR to become stale.

You as commenting people also have to value and respect the work that the person doing the PR did.
And that also means that if the points/issues raised have been covered or talked about and the consensus then was that it is if no issue after all, then there should be no need to block this from moving forward.
Incremental changes are also way better than no progress at all.

**Comment by bravo-kernel** [comment]
Apologies if I caused any grievance here, that was not my intention. I was under the impression there was consensus of not using webroot so (to me) the adjustment seemed logical and up to mr. @dereuromark. In that context I might easily have misinterpreted things as "thanks for the time taken to think about improving this but please go fix it yourself", my bad.

**Comment by dereuromark** [comment]
I want each other to work together - not block each other from doing sth :) That's all.

**Comment by dereuromark** [comment]
I will close this now. If someone wants to see it happening in this or a different form, please PR.

**Pull request closed without merging**
