### PR TITLE
Add Shell Helper directory

### PR DESCRIPTION
**Pull request by bcrowe**
Refs https://github.com/cakephp/bake/pull/101 and https://github.com/cakephp/cakephp/pull/6666

### CODE REVIEW

**Comment by markstory** [comment]
:clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap:

**Comment by ADmad** [comment]
Ehm.. :-1:.   It's not often people are going to make shell helpers imho, so no extra empty directories please.

**Comment by josegonzalez** [comment]
-1

**Comment by antograssiot** [comment]
I agree with @Admad :-1:

**Comment by ADmad** [comment]
Strike three.

**Comment by josegonzalez** [comment]
YOU'RE OUT!

**Pull request closed without merging**
