### PR TITLE
make AjaxView extends View instead of AppView

### PR DESCRIPTION
**Pull request by ayman-alkom**
I found this more logical then we are more free in playing with AppView

### CODE REVIEW

**Comment by markstory** [comment]
Why?

**Comment by ayman-alkom** [comment]
In the case we use the custom view class of BootstrapUI plugin `UIView`, it made conflicts to the debug_kit plugin.
I found that making the AjaxView separated of AppView will be more clear

**Comment by markstory** [comment]
My worry is that we've documented `AppView` as the base class of application views which includes this view class. Not extending `AppView` will mean that custom helpers needed in all views will not be present in `AjaxView`.

**Comment by ayman-alkom** [comment]
> Not extending AppView will mean that custom helpers needed in all views will not be present in AjaxView

I 'm not sure, but I think that we don't use any of the helpers in `AjaxView`.

**Comment by ADmad** [comment]
> I 'm not sure, but I think that we don't use any of the helpers in AjaxView.

`AjaxView` itself doesn't load any helpers but since it extends `AppView` any helpers you load in `AppView` (which is the recommended way) they would be available to `AjaxView` too.

I too don't like like this change. Most people would expect settings done in `AppView` to be able in `AjaxView` too since it only difference is `AjaxView` uses an empty layout.

@ayman-alkom You can make required change in your own app but the official app skeleton should remain the same.

**Comment by ayman-alkom** [comment]
@ADmad I don't know why some one will need FormHelper for example in AjaxView, AjaxView and AppView are completely different  IMO.

I use AjaxView Just for REST API, and don't know if some one using it for the other target 

> You can make required change in your own app but the official app skeleton should remain the same.

Anyone know that :)

**Comment by ADmad** [comment]
> I use AjaxView Just for REST API, and don't know if some one using it for the other target

Most people use AjaxView to return HTML fragments.  What response format are you using for your REST API?  Most ppl would use json or xml and hence JsonView or XmlView not AjaxView.

**Comment by dereuromark** [comment]
Or my Ajax Plugin which has an json powered Ajax View class.

**Comment by ayman-alkom** [comment]
> Most ppl would use json or xml and hence JsonView or XmlView not AjaxView.

yes @ADmad you are right, I forgot JsonView and XmlView, in fact I using them, but  anyway  this change solved my Debugkit issue and other issues related to ajax requests. and you are free consider AjaxView as JsonView must be separated by default or not.

**Comment by ayman-alkom** [comment]
@dereuromark I looked at your [AjaxView](https://github.com/dereuromark/cakephp-ajax/blob/master/src/View/AjaxView.php#L22) and sow it extend the View and not AppView

**Comment by ADmad** [comment]
>  anyway this change solved my Debugkit issue

What debugkit issue?

**Comment by ayman-alkom** [comment]
## In the case it extends View
untitled

## In the case it extends AppView:
my assets comes again every time I view a DebugKit panel, note that I 'm using UIView and this may be able to solved in other way but didn't search more because I found this is the best solution to me.

untitled2

**Comment by ionas** [comment]
I think we should rather offer an `HtmlView` or something long those lines and allow specifying helpers for specific Views, so that you can opt-in/opt-out of setting helpers for `AjaxView`.

You can also create your own XhrAppController and extent your controllers from that AppController which possibly would not load any helpers... (also create an HtmlAppController which does, both derive from AppController, your action holding controllers then from XhrApp-/HtmlAppController) etc.

**Comment by ADmad** [comment]
I'll let @markstory look into the debugkit issue :smile:

**Comment by markstory** [comment]
One way around the DebugKit issue is for DebugKit to provide its *own* AjaxView that userland code can't muck about with.

**Comment by lorenzo** [comment]
Since AjaxView is a class you can own, you can also make it extend whatever you want in your project. I think AppView is the best default.

**Comment by markstory** [comment]
Closing as I feel the current setup is a good default. I will fix the debugkit issue so others don't bump into this specific issue.

**Pull request closed without merging**
