### PR TITLE
Ignored TestCase + whitelisted plugins `src`

### LINKED ISSUE #333: Remove coverage for TestCase
That issue sounds strange, I know. What I mean is that we're currently generating test coverage for tests. 

To be more explicit, I mean changing this:

```xml
    <!-- Ignore vendor tests in code coverage reports -->
    <filter>
        <blacklist>
            <directory suffix=".php">./vendor/</directory>
        </blacklist>
        <whitelist>
            <directory suffix=".php">./tests/TestCase/</directory>
            <directory suffix=".php">./src/</directory>
        </whitelist>
    </filter>
```

To this:

```xml
    <!-- Ignore vendor tests in code coverage reports -->
    <filter>
        <blacklist>
            <directory suffix=".php">./vendor/</directory>
            <directory suffix=".php">./tests/TestCase/</directory>
        </blacklist>
        <whitelist>
            <directory suffix=".php">./src/</directory>
        </whitelist>
    </filter>
```

Or, even better, to this:

```xml
    <!-- Ignore vendor tests in code coverage reports -->
    <filter>
        <blacklist>
            <directory suffix=".php">./vendor/</directory>
            <directory suffix=".php">./tests/TestCase/</directory>
        </blacklist>
        <whitelist>
            <directory suffix=".php">./src/</directory>
            <directory suffix=".php">./plugins/*/src/</directory>
        </whitelist>
    </filter>
```

So we include the coverage for user-included plugins.

Is there any reason why the `TestCase` is under the `whitelist` tag? Removing it does not affect my test coverage over `src`.

### PR DESCRIPTION
**Pull request by elboletaire**
closes #333

### CODE REVIEW

**Comment by lorenzo** [comment]
:+1:

**Comment by ADmad** [comment]
I don't think the blacklist is necessary since whitelist is provided.

**Comment by elboletaire** [comment]
> I don't think the blacklist is necessary since whitelist is provided.

True, but why are we ignoring `vendors` then?

**Comment by ADmad** [comment]
I don't know how we ended up in current state but the <blacklist> tag can be removed.

**Comment by elboletaire** [comment]
You mean, the entire `blacklist` tag, right?

**Comment by lorenzo** [comment]
@elboletaire yes

**Comment by elboletaire** [comment]
easy peasy

**Comment by lorenzo** [comment]
thanks @elboletaire :)

**Comment by elboletaire** [comment]
you're welcome :)

**Pull request merged**
