### PR TITLE
Use `psysh` for `cake console` instead of `boris`

### PR DESCRIPTION
**Pull request by antograssiot**
so even windows users can enjoy this feature without using a VM.
http://psysh.org/

### CODE REVIEW

**Comment by antograssiot** [comment]
I took care of th CS error

**Comment by kamui545** [comment]
I was thinking about the same few days ago, I think it's a good move :+1:

**Comment by markstory** [comment]
Looks like a big improvement to me.

**Comment by lorenzo** [comment]
This looks like a big improvement to me as well. We may want to register our own debugger to psysh at some point. I'm going to merge this so we can iterate over it :)

Great jon @antograssiot !

**Comment by dereuromark** [comment]
It will need a few extensions to work flawless it seems:
```
psy/psysh suggests installing ext-pcntl (Enabling the PCNTL extension makes PsyS
H a lot happier :))
psy/psysh suggests installing ext-posix (If you have PCNTL, you'll want the POSI
X extension as well.)
psy/psysh suggests installing ext-readline (Enables support for arrow-key histor
y navigation, and showing and manipulating command history.)
psy/psysh suggests installing ext-pdo-sqlite (The doc command requires SQLite to
 work.)
```
But looks good and I will give it a spin as soon as possible :)

**Comment by ceeram** [comment]
@dereuromark not very different from boris: https://github.com/borisrepl/boris/blob/master/composer.json

**Comment by ceeram** [comment]
On boris they are hard requirements instead of suggests

**Pull request merged**
