### PR TITLE
Update home.ctp

### PR DESCRIPTION
**Pull request by ionas**
Please review the error message itself, written to errors.log, flagged as warning.
Could you think of a more concise English sentence pointing at that controller/action/template?
Maybe Pages::display/home ?

Ref: https://github.com/cakephp/app/issues/43#issuecomment-38471491
Ref: https://github.com/cakephp/app/issues/43#issuecomment-38473872

Note: I'd actually include an error message, because where is the security issue here with being transparent?

### CODE REVIEW

**Comment by bravo-kernel** [comment]
How about adding a (prominent) warning to the `home.ctp` page itself as well to inform new users about this 🕳?

**Comment by ADmad** [comment]
> How about adding a (prominent) warning to the home.ctp page itself as well to inform new users about this?

:+1:  since most newbies wouldn't check the logs either. So better to try and make them aware while the page is accessible :)

**Comment by lorenzo** [comment]
Why not just show the page minus the status checks?

**Comment by ionas** [comment]
@lorenzo with an info box saying "Set debug to true, to see setup status check results"?

**Comment by ionas** [comment]
Ref: https://github.com/cakephp/app/pull/320

**Comment by bravo-kernel** [comment]
Please note that **this page will not be shown** when you turn off debug mode. To disable this security measure remove the NotFoundException in src/Template/Pages/home.ctp.

**Comment by ionas** [comment]
@bravo-kernel well I tend to agree with @lorenzo - would you be so kind and adapt to that? E.g. a notification that status check results will only be shown when debug is turned on? Is that a good compromise?

**Comment by bravo-kernel** [comment]
Unless I am totally misreading the intended end-result... not really and I feel backed by [these arguments](https://github.com/cakephp/app/pull/225): no page at all in non-debug mode by default.

**Comment by ionas** [comment]
I can see reasons for both. I just need a decision and then change it to whatever fits.
@ADmad seems to also have an opinion.
I tend to agree with @AD7six that I'd like this site to not be accessible if the app is set into production mode. By doing so there is no need to remove the page (I usually rename it to cake.ctp or setup.ctp).

**Comment by jadb** [comment]
@ionas, isn't renaming the same as removing? 

IMO, `home.ctp` should just return the usual 404 when not in debug mode. 

Maybe better documenting it in the book if it's to help new users?

**Comment by ionas** [comment]
@jadb what I mean is, I keep the file around for testing the setup in an convenient way and have another default homepage. The file should then still not be accessible unless debug is turned on.

**Comment by dereuromark** [comment]
So how about https://github.com/cakephp/app/pull/320/files with **always** display that error message?
This should make it perfectly clear that deploying this default home.ctp is pointless.

**Comment by bravo-kernel** [comment]
I don't think that PR would help people using cakebox or similar bridged vm @dereuromark since 127.0.0.1 would not be applicable and thus... white page again.

**Comment by dereuromark** [comment]
I just said: ALWAYS display, so no need for the env check :) I will refactor.

**Comment by markstory** [comment]
Closing in preference of #320

**Comment by ionas** [comment]
* Sorry but this PR also wrote a warning. And set HTTP 403 instead of 404. If both are not deemed a good idea, okay.
* What about @lorenzo wish to render the page without the stats?
* What about the general wish to add a note that in case debug is turned off this page will vanish?

**Comment by markstory** [comment]
If the page doesn't leak information I don't see why we couldn't remove the exception.

**Pull request closed without merging**
