### PR TITLE
Fix TypeError when action is called without any arguments.

### LINKED ISSUE #833: TypeError controller
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Application Skeleton Version: latest master

### What you did
Someone accesses Pages as `/pages/`

### What happened

> [TypeError] Argument 1 passed to App\Controller\PagesController::display() must be of the type string, null given, called in /var/www/.../site/vendor/cakephp/cakephp/src/Controller/Controller.php on line 531 in /var/www/.../site/src/Controller/PagesController.php on line 73

### What you expected to happen
No internal server error but normal 404

Looking at the stacktrace we either need to make `public function display(string ...$path): ?Response` nullable
or we need to make sure a (casted) empty string is used instead of null?

### PR DESCRIPTION
**Pull request by ADmad**
Fixes #833.

### CODE REVIEW

**Comment by othercorey** [comment]
Looks ok.

**Comment by garas** [comment]
It is regression in `Cake\Controller\ControllerFactory::invoke()`.

In 4.1, action is invoked with no arguments, in 4.2 with one argument `null`.

**Comment by othercorey** [comment]
> It is regression in `Cake\Controller\ControllerFactory::invoke()`.
> 
> In 4.1, action is invoked with no arguments, in 4.2 with one argument `null`.
> 
> It needs to handle variadic parameters.

Can you open an issue for this?

**Comment by garas** [comment]
I opened new issue at https://github.com/cakephp/cakephp/issues/15441.

**Comment by markstory** [comment]
Seems like we should fix the ControllerFactorynissue instead.

**Comment by garas** [comment]
Fixed in https://github.com/cakephp/cakephp/pull/15445

**Pull request closed without merging**
