### PR TITLE
Read error handler config instead of consuming in bootstrap.

### PR DESCRIPTION
**Pull request by ADmad**
This allows the config to be reused to register a new handler post
bootstrapping, by only only modifying required options and keeping the rest
same as those set in config/app.php

Use case: Crud plugin's ApiListener needs to set a custom exception render. Since in 3.x only way to change that is register a new error handler you need access to the error config so that it can only change the exception renderer class and use the rest of the settings same as what developer sets in his app config.

### CODE REVIEW

**Comment by josegonzalez** [comment]
Any movement on this?

**Comment by lorenzo** [comment]
not so far @josegonzalez... do you want to take this task?

**Comment by josegonzalez** [comment]
No lol I'm just bumping to see if anyone was gonna do anything :P

**Comment by AD7six** [comment]
A low-effort solution might be to just make consumed config retrievable (move it under the config-key "Consumed"?).

**Comment by dereuromark** [comment]
Until we can resolve this, we maybe should just use read() for now?

**Comment by markstory** [comment]
Using read() is a low effort solution that solves some of the issues described here.

**Comment by ADmad** [comment]
Rebased and merged.

**Pull request merged**
