### PR TITLE
Add bash completion script.

### PR DESCRIPTION
**Pull request by ADmad**

### CODE REVIEW

**Comment by dereuromark** [comment]
Does that mean it doesnt need any of the extraction tools/ideas like
https://github.com/dereuromark/cakephp-ide-helper/compare/command-line
to get it working for bash?

Is that true for both commands and shell?

**Comment by ADmad** [comment]
It just works:tm: once you follow https://book.cakephp.org/4/en/console-commands/completion.html#how-to-enable-bash-autocompletion-for-the-cakephp-console

**Comment by dereuromark** [comment]
Yeah, it "kind of" works.
It seems to have some troubling output once you reach the end, instead of just continuing.
But looks like an improvement for sure.
I wonder if we should add a composer script to quickly generate those 3 types: `composer completion` or `composer complete`

**Comment by ADmad** [comment]
> It seems to have some troubling output once you reach the end, instead of just continuing.

Yes, there are some issues with the `CompletionCommand` (or maybe this script) which need to be addressed. 

> I wonder if we should add a composer script to quickly generate those 3 types: composer completion

That would be nice.

**Pull request merged**
