### PR TITLE
Remove default serialization of all view vars.

### PR DESCRIPTION
**Pull request by ADmad**
This is an unsafe default and a comment warning is not enough.

### CODE REVIEW

**Comment by dereuromark** [comment]
As alternative, how about putting it into a protected method and then using it commented out?
This way you can activate with a single line commenting in.

**Comment by markstory** [comment]
Refs cakephp/cakephp#11506

**Comment by chinpei215** [comment]
I would suggest to stop loading `RequestHandlerComponent` by default. Even if we remove the problematic code, Cake3 applications would still leak sensitive information, as Bake generates `$this->set('_serialize', ['users']);` or something.

Also, I think it would be better to announce this issue officially, as almost all Cake3 applications would be affected by this issue. Though I have already announce this issue to people in **#japanese** channel on our Slack, I am not sure what is the best way to secure their applications. For now I have recommended to remove `$this->loadCompnent('RequestHandler');` from their `AppController`.

**Comment by ADmad** [comment]
@dereuromark We would still be providing a way to use the framework in an unsafe way so best to remove it.

@chinpei215 I am not in favor removing `RequestHandlerComponent` from being loaded by default. I am pretty sure it's used in most apps. While bake might be generating `$this->set('_serialize', ['users']);` is pretty evident that if you serialize `$users` all user data is gonna end up in the output unless you restrict the fields.

**Comment by inoas** [comment]
Also by default sensitive fields such as passwords are hidden by bakes defaults AFAIR.
But if it must be we can outcomment the `$this->set('_serialize', ['users']);` in bake instead of the RequestHandler?

**Comment by chinpei215** [comment]
> While bake might be generating $this->set('_serialize', ['users']); is pretty evident that if you serialize $users all user data is gonna end up in the output unless you restrict the fields.

I disagree. I think any beginners would not touch the code as they wouldn't understand what it means.

**Comment by markstory** [comment]
Removing RequestHandlerComponent by default will make building API's require a bit more work.  I think making APIs easy to build should be something we enable as it is a requirement for new applications that use client side frameworks.

**Comment by chinpei215** [comment]
Seriously? I don't think adding one line `$this->loadComponent('RequestHandler')` is a hard work.
Imagine if you have a users' profile page on your website. The page doesn't show you any sensitive information, such as `email`, `family_name`, `given_name` , `address`, and so on. It shows people `nickname` only. However, if you access the page with `Accept: application/json` header, you will see those sensitive information. It is a very bad behavior.
When we consider security issue, it's best to be on the safe side. When we compare 'adding a single `$this->loadComponent('RequestHandler')` (otherwise you cannot get json response)' with 'removing `_serialize` from your baked code (otherwise you will expose any sensitive information), the latter wins.
If you still have not changed your opinion, let's ask Mozilla Secure Open Source for their opinions. I think they overlooked this issue. But if they knew this issue, they would have marked this as critical. Because any websites made with Cake3 are possible to expose any sensitive information if the developers don't have enough knowledge about `RequestHandler`. I have never used the feature in 2.x. So if I were made a website with Cake3, my website would have become vulnerable.

**Comment by inoas** [comment]
What about shipping a prefixed ApiAppController with requesthandler and auto serialization enabled?

**Comment by chinpei215** [comment]
I wouldn't oppose it.

**Comment by markstory** [comment]
@chinpei215 Those are fair points, and you're right adding one component load is not hard.

**Comment by lorenzo** [comment]
Maybe we should have a different component (or controller method) to enable automatic json views?

**Comment by chinpei215** [comment]
It could be an another approach.

**Comment by saeideng** [comment]
how happen if set `$this->set('_serialize', false);` here ?

**Comment by rchavik** [comment]
Related #501

**Comment by markstory** [comment]
Backported to `master` in 84ec633f3127cd431696cea5c2cb92756072c53b

**Pull request merged**
