### PR TITLE
Remove web test runner, and only use phpunit.

### PR DESCRIPTION
**Pull request by markstory**
This set of changes implements the ideas in #12. I have mixed feelings about removing the `test.php` file.

In the :+1: side for keeping `test.php`
- It is easier for CLI newbies to get testing working.
- It has a nice coverage view per file.

On the :-1: side of keeping `test.php`:
- It is a snowflake. Both in CakePHP and in PHP in general. No other frameworks maintain their own web runner for PHPUnit. I'm considering either contributing to/forking VisualPHPUnit so we can provide a more general use test runner.
- CakePHP has a non-trivial amount of code dedicated to supporting the web-runner. I'd like to see that go away.

I think most CLI newbies are also people who use full featured IDE's. Most good IDE's have a way of integrating with PHPUnit. IDE integration might be more valuable/useful to this group. It certainly is less work once you get it working.

### CODE REVIEW

**Comment by burzum** [comment]
>  I'm considering either contributing to/forking VisualPHPUnit so we can provide a more general use test runner.

I agree. Actually it already works with CakePHP3. Guess there are things we can do to make it better or something like that?

> CakePHP has a non-trivial amount of code dedicated to supporting the web-runner. I'd like to see that go away.

Yes, remove it! :+1:

**Comment by dereuromark** [comment]
One would need a plugin for a better VisualPHPUnit integration. Right now it is not too feasible to use.

**Comment by leighmackay** [comment]
@markstory  
> It has a nice coverage view per file.

That is what I personally miss. Would it be possible to have another tab on the wonderful DebugKit that just shows test coverage? might be a silly idea.

**Comment by dakota** [comment]
@leighmackay running phpunit with `--coverage-html` gives you an even nicer coverage view :+1:

**Comment by leighmackay** [comment]
@dakota  Thank you. Yes, I run use that, but miss being able to click and see it.

**Comment by leighmackay** [comment]
You guys are right, it's not needed, forget my request. 

:+1:  keeping it out.

**Pull request merged**
