### PR TITLE
Ensure post install script runs when creating project.

### PR DESCRIPTION
**Pull request by ADmad**
Refs #355

### CODE REVIEW

**Comment by ionas** [comment]
Thanks for taking care!

**Comment by lorenzo** [comment]
good stuff

**Comment by ADmad** [comment]
A new release show be done.

**Comment by lorenzo** [comment]
@ADmad go for it!

**Comment by chinpei215** [comment]
@ADmad Wouldn't installer run twice if users are using an old version of composer?

**Comment by ADmad** [comment]
@chinpei215 I checked with composer `1.0.0-beta1` and it does run the script twice. Other than being unexpected having it run twice won't cause any actual problem.

We can remove `"post-install-cmd"` if we want to run the script only when creating the project and not when running composer install or update.

**Comment by chinpei215** [comment]
@ADmad It sounds reasonable to me. If we can remove `"post-install-cmd"`, as positive side-effect, it would also solve #354. But as I am not familiar with composer, my opinion wouldn't be reliable. I misunderstood `composer.lock` as a file to prevent duplicate execution until yesterday :stuck_out_tongue:

**Comment by ADmad** [comment]
@chinpei215 Until yesterday I thought create project was akin to install, but apparently composer says "Meh, you are such a n00b, I'll do an update instead." :stuck_out_tongue: 

@ionas Want to do the honors of removing the the post install hook?

**Comment by ionas** [comment]
I'd rather make sure (newbie) users got a recent composer version. See above.

**Comment by ionas** [comment]
Here is my suggestion: https://github.com/cakephp/app/pull/358
It does assume that composer is recent, thus the above PRs to the docs.

**Pull request merged**
