### PR TITLE
Small app skeleton review

### PR DESCRIPTION
**Pull request by andtxr**
* Some DocBlocks improvements and fixes
* normalize & foundation are now updated

### CODE REVIEW

**Comment by markstory** [comment]
The CSS changes have caused some visual regressions:

* Tables are no longer full width on the index page.
* Tables of associations on view pages are no longer full width.

**Comment by jhli** [comment]
If I get to it I'll prep a small PR to reduce dependencies to grid mixins if desired, to reduce regressions, issues like this and cake/bake upgrade issues.

**Comment by andtxr** [comment]
I have tested it with some bake and everything looked fine. I will review it today.

**Comment by andtxr** [comment]
@jhli I like the idea, I would like to start a better stylesheet for baked templates, or even a customized foundation theme - once it is already used as structural base.

**Comment by andtxr** [comment]
Actually, the work was already done. :dancer: 

Amazing work in cakephp/cakephp#6679

**Comment by markstory** [comment]
Thanks @andtxr

**Pull request merged**
