### PR TITLE
minimum-stability stable

### PR DESCRIPTION
**Pull request by ionas**
Ref: https://github.com/cakephp/app/commit/a4406a02dc102c10103fc5b65bab0e549565a1ee
Ref: https://gist.github.com/ionas/a900b900fc98909f7372 (source of the issue was minimum-stability dev)

### CODE REVIEW

**Comment by dereuromark** [comment]
For new apps this makes probably sense :+1:

**Comment by dereuromark** [comment]
PS: does adding prefer-stable=>true have the same effect?

**Comment by ionas** [comment]
It is already in, and no, it did not (for me, see the gist).

**Comment by jadb** [comment]
I merged because it was to be reverted by @lorenzo's comment on the commit that initially changed it. I believe it was while working on cakephp/chronos and while it wasn't stable yet. 

This setting should be the promoted default for new apps in general (unless one specifically wants dev stability).

**Pull request merged**
