### PR TITLE
Import Cake\Codeception\Console\Installer

### PR DESCRIPTION
**Pull request by szepeviktor**
Minus one variable 🚀

### CODE REVIEW

**Comment by szepeviktor** [comment]
Thank you.

**Comment by othercorey** [comment]
Should we even suggest this anymore?

**Comment by ADmad** [comment]
Probably not, the codeception plugin isn't maintained.

**Comment by LordSimal** [comment]
The class `Cake\Codeception\Console\Installer` doesn't seem to exist for me. I am on CakePHP 4.3.
Or am I missing something?

**Comment by ndm2** [comment]
It's in the [**codeception plugin**](https://github.com/cakephp/codeception/blob/master/src/Console/Installer.php).

**Comment by LordSimal** [comment]
I was just confused to see code/use statements which are not resolvable in the "base" app template because the plugin is not in the composer.json

If this is intended then forget that I asked 😄

**Pull request merged**
