### PR TITLE
PHPDoc | Missing @throws tag

### PR DESCRIPTION
**Pull request by AdrienLZ**
Correct PHPDoc warning about missing @throws tag

### CODE REVIEW

**Comment by ADmad** [comment]
`initialize()` doesn't throw any exception directly. There could be an exception bubbling up from one of the method calls made inside it but would be try for pretty much every method throughout the code.

**Comment by AdrienLZ** [comment]
> `initialize()` doesn't throw any exception directly. There could be an exception bubbling up from one of the method calls made inside it but that would be true for pretty much every method throughout the code.

It complain on **loadComponent**.

**Comment by dereuromark** [comment]
Exactly, you should never document non first level exceptions here as this cannot be automated or enforced, leading to copy paste issues and lies.

**Comment by dereuromark** [comment]
In your IDE? Fix you config there, this is a developer issue.

**Comment by dereuromark** [comment]
E.g. In phpstorm: 0 level only.

**Comment by AdrienLZ** [comment]
Thanks @ADmad  @dereuromark  for the explanation.

**Pull request closed without merging**
