### PR TITLE
Add warning against default serializing setting.

### PR DESCRIPTION
**Pull request by ADmad**
@rchavik has brought this up a while back.

### CODE REVIEW

**Comment by cleptric** [comment]
Thx 😀

**Comment by lorenzo** [comment]
Should it maybe be surrounded by `if debug == true else { throw HelpfulException }` ?

**Comment by davidyell** [comment]
I always delete this when I'm creating my project anyway. No idea why it's even in the core. To me it feels like the old Cake magic or a type of 'hack'.

**Comment by josegonzalez** [comment]
@lorenzo That seems extra hacky to me...

**Comment by lorenzo** [comment]
@josegonzalez I just find unhelpful that we provide code that is not meant to be actually there. So, why have it?

**Comment by inoas** [comment]
I am either pro removing or for changing it to warning that goes to the log files in production.
Adding an Exception can result into "deployment-day" and you realize that once you switch from debug true to debug false you suddenly see exceptions you did not expect to see.

**Comment by davidyell** [comment]
There is also a chance that if it's changed to a log, it will not be noticed. If it's logged on every request that will produce a big log file pretty quickly.

**Comment by ADmad** [comment]
> No idea why it's even in the core

It's not in core, it's in the app skeleton which is meant to help people going quickly with development. I had added this in the past as I seen many newbies struggle figuring out what proper vale to set for `_serialize` to get the serialization working.

Hopefully in 4.x we can come up with a better way to handle what to serialize. Settings this view var feels a bit hacky now.

**Pull request merged**
