### PR TITLE
Remove unnecessary `else`

### PR DESCRIPTION
**Pull request by alecho**

### CODE REVIEW

**Comment by lorenzo** [comment]
So after asking if you don't want to set the permissions it will set the permissions again?

**Comment by alecho** [comment]
Ah your right. I read those lines a couple times and I thought I was right, hence the PR. I'll close.

**Comment by jadb** [comment]
@lorenzo that's about right. It will set the permissions if you choose not to (as you said) and will double-set them if you choose to set them in the first place (interactive mode). 

That been said, I don't think that's the intended behaviour. Is it?

**Comment by jadb** [comment]
hmm - you guys were quicker :+1:

**Pull request closed without merging**
