### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by EOM**
This will add more compactness to the CakePHP to work in an AppEngine environment with Flex. It only remains to create an app.yaml as requested by AppEngine and that's it.

### CODE REVIEW

**Comment by dereuromark** [comment]
Shouldn't at least intl be optional (if you dont need any of it) and thus be suggest or require-dev?
Making this a hard requirement in the past had causes people some grieve.

**Comment by dereuromark** [comment]
I see intl still in here, though:
https://github.com/cakephp/cakephp/blob/master/composer.json#L32-L33

**Comment by ADmad** [comment]
As pointed out by @dereuromark, intl and mbstring are already added as dependencies of CakePHP core. So why is duplicating then in app skeleton necessary?

https://github.com/cakephp/cakephp/blob/82fc4b783b0411d73565a7e49122dd7e8721f7ed/composer.json#L32

**Comment by EOM** [comment]
Hello,
Because AppEngine PHP Flex, from Google, looks if it has libraries required in the composer.json root, not in the other composer.json like the one that has CakePHP (https://github.com/cakephp/cakephp/blob/master/composer .json # L32-L33)
Of this menar with there is no error and it is simpler to execute the installation in AppEngine.

More information (Alternative option load ext PHP): 
https://cloud.google.com/appengine/docs/flexible/php/runtime#dependencies

**Comment by markstory** [comment]
The new composer requirements are reasonable to me. They will continue to be dependencies of CakePHP in the foreseeable future. Having them here helps make deployment in appengine easier and doesn't add cruft that needs to be removed for other environments.

**Comment by EOM** [comment]
@ADmad  Yes, in AppEngine only intl. 
Ext mbstring is enable for default in AppEngine Flex

**Comment by dereuromark** [comment]
Closing as the main library CakePHP needs to declare this, not the project level.

**Pull request closed without merging**
