### PR TITLE
Create `tmp` and `logs` on post-install hook

### PR DESCRIPTION
**Pull request by jadb**
This reverts the changes made in #238 (they aren't [behaving as expected](https://github.com/cakephp/app/issues/237#issuecomment-96204717)) and implements what was last suggested in #237.

### CODE REVIEW

**Comment by lorenzo** [comment]
:+1:

**Comment by ADmad** [comment]
:+1:

**Comment by bravo-kernel** [comment]
:clap:

**Comment by elboletaire** [comment]
:+1: :clap:

**Comment by bravo-kernel** [comment]
So happy with this hook, it's awesome

**Pull request merged**
