### PR TITLE
[.gitignore] Remove inline comments

### PR DESCRIPTION
**Pull request by jacricelli**
.gitignore does not support inline comments.

### CODE REVIEW

**Comment by dereuromark** [comment]
Why? Some of those seem to be useful additions to clarify the file/folder. And they dont cost anything.

**Comment by inoas** [comment]
Well I could not find docs saying that you can actually put things in one line. I am not sure if it is just fault tolerance on behalf of git or a feature to use inline comments. So I have created #548 to keep the comments as block comments. It is not nearly as nice but also here https://github.com/github/gitignore I could not find any appended inline comments.

**Comment by markstory** [comment]
Closing as the comments were moved in #548

**Comment by jacricelli** [comment]
@dereuromark @inoas
```
git check-ignore --non-matching --verbose config/app.php tmp/test.tmp .sublime-project .sublime-workspace a.swp b.swo .idea/test.xml logs/error.log
.gitignore:3:/config/app.php	config/app.php
.gitignore:6:/tmp/*	tmp/test.tmp
::	.sublime-project
::	.sublime-workspace
::	a.swp
::	b.swo
::	.idea/test.xml
.gitignore:5:/logs/*	logs/error.log
```

**Comment by inoas** [comment]
@jacricelli thankd for bringing it up and pointing it out :+1:

**Pull request closed without merging**
