### PR TITLE
5.x: use plugin loading via configuration array

### PR DESCRIPTION
**Pull request by LordSimal**
I really like the new plugin loading functionality via `config/plugins.php`. 

This allows the Application class to be pretty clean.

### CODE REVIEW

**Comment by LordSimal** [comment]
Seems weird that the DebugKit is not being loaded in the tests...

**Comment by LordSimal** [comment]
Ah, we do a `include_once` [here](https://github.com/cakephp/cakephp/blob/5.x/src/Http/BaseApplication.php#L186) but these tests require that this file can be loaded multiple times in the same PHP process.

**Comment by ADmad** [comment]
Thanks, this was my final goal, just never got around to finishing it :)

I eventually want plugin installing and enabling to be a single command process, not the 2 steps of `composer install` and `bin/cake plugin load`.

**Comment by LordSimal** [comment]
> I eventually want plugin installing and enabling to be a single command process

yes, that would be the best scenario

**Comment by markstory** [comment]
I like the approach of using `config/plugins.php` more consistently :+1:

**Comment by LordSimal** [comment]
To get 8.1 lowest working here we would have to adjust the composer.json to `"cakephp/cakephp": "^5.0.1",`

**Pull request merged**
