### PR TITLE
enable in PagesController only to not slow down rest of testsuite

### PR DESCRIPTION
**Pull request by swiffer**
**PLEASE NOTE:**

This is only a issue tracker for issues related to the CakePHP Application Skeleton.
For CakePHP Framework issues please use this [issue tracker](https://github.com/cakephp/cakephp/issues).

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

The best way to propose a feature is to open an issue first and discuss your ideas there before implementing them.

Always follow the [contribution guidelines](https://github.com/cakephp/cakephp/blob/master/.github/CONTRIBUTING.md) guidelines when submitting a pull request. In particular, make sure existing tests still pass, and add tests for all new behavior. When fixing a bug, you may want to add a test to verify the fix.

### CODE REVIEW

**Comment by ADmad** [comment]
Thanks, but this is not necessary. The app skeleton doesn't get updated often enough to warrant this change.

**Comment by swiffer** [comment]
Okay, i've had the PagesController still present in my application and then it got relevant.

**Comment by ADmad** [comment]
The app skeleton is just a starting point. You can do whatever you want after initially creating your app using this repo :)

**Comment by swiffer** [comment]
That's what I did :) totally fine closing this one

**Pull request closed without merging**
