### PR TITLE
Adding CSRF Protection middleware into Application.php

### PR DESCRIPTION
**Pull request by LubosRemplik**
related to #540

### CODE REVIEW

**Comment by HorlogeSkynet** [comment]
Hello !

Should we enable `httpOnly` by default ? 🤔

Ciao 👋

**Comment by LubosRemplik** [comment]
Not sure, if yes I would change default options here https://github.com/cakephp/cakephp/blob/master/src/Http/Middleware/CsrfProtectionMiddleware.php#L52

**Comment by HorlogeSkynet** [comment]
I would definitely too ! Does anyone know why this choice has been particularly made ?
I mean, for "standard" apps, this could and should be set to `true` without any problem, am I wrong ? :thinking:

**Comment by markstory** [comment]
The default is `false` to retain backwards compatibility with the CsrfComponent. We cannot change the default value until 4.x. If you'd like to change it please open a pull request targetting `4.x`.

**Comment by LubosRemplik** [comment]
But still we can add the middleware into the Application.php with default settings, can't we?

**Comment by markstory** [comment]
While the default httpOnly value is false, it could be set to `true` in the application template.

**Comment by LubosRemplik** [comment]
Thanks @ravage84 and @markstory for suggestions, both added

**Pull request merged**
