### PR TITLE
Add fix for the httpoxy vulnerability

### PR DESCRIPTION
**Pull request by ravage84**
Refs https://github.com/cakephp/cakephp/issues/9137#issuecomment-233637635

### CODE REVIEW

**Comment by ADmad** [comment]
This should be added to `webroot/.htaccess` as for production it's recommended to set server's document root to `webroot` and thus this `.htaccess` won't be hit.

**Comment by dereuromark** [comment]
Maybe we can also add a note to this htaccess that this recommended to use for local dev only.

**Comment by jippi** [comment]
i think it should be `on` by default, 99,999% of the users wouldn't know it, but would out of the box be protected :)

**Comment by markstory** [comment]
More pull requests are always welcome :smile:

**Pull request merged**
